### ISSUE TITLE
Add support for sinking to stream in separate AWS account

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/kinesis-tee#1]

**Comment by alexanderdean** [comment]
Bringing forwards given it was suggested by a customer.

**Comment by alexanderdean** [comment]
@ninjabear - you'll have to update the config format to accommodate credentials for the target stream, and the README to clarify this new functionality...

**Comment by ninjabear** [comment]
cool, sounds good!

**Comment by alexanderdean** [comment]
Need to figure out what options we have for attaching the credentials for the other AWS account...

**Comment by alexanderdean** [comment]
This is done
